### ISSUE TITLE
weird `pub` issue

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1708]
Weird `pub` issues since update to
> Dart VM version: 2.0.0-dev.0.0 (Mon Sep 18 09:03:36 2017) on "macos_x64"

After adding a package that depends on Flutter to a library package and running `pub upgrade` I got an error that some file wasn't found.
I don't have the details anymore (screen buffer too small)

Then I run `pub cache repair` which was stuck eventually on a global activated package from a local path with some error message (also not in the buffer anymore).
The next `pub cache repair` run it wasn't stuck anymore, but at the end I got

```
Downloading yamlicious 0.0.5...
tar: Failed to set default locale
Reinstalled 252 packages.
Reactivating coverage 0.9.2...
Precompiling executables... 
Failed to precompile coverage:run_and_collect:
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:9)
#1      main (file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/coverage-0.9.2/bin/run_and_collect.dart:4:41)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Failed to precompile coverage:format_coverage:
```

the next `pub cache repair` caused

```
tar: Failed to set default locale
Downloading yaml 2.1.12...
tar: Failed to set default locale
Downloading yamlicious 0.0.5...
tar: Failed to set default locale
Reinstalled 251 packages.
Reactivating coverage 0.9.2...
Failed to reactivate coverage 0.9.2: Could not find a file named "pubspec.yaml" in "/Users/zoechi/.pub-cache/hosted/pub.dartlang.org/coverage-0.9.2".
Reactivating dart_style 1.0.7...
Precompiling executables... 
Loading source assets... 
Precompiled dart_style:format.
Installed executables dartfmt and dartformat.
Reactivating grinder 0.8.0+3...
Precompiling executables... 
Failed to precompile grinder:init:

Failed to precompile grinder:grinder:

failed with exit code 1
#0      run (package:grinder/src/run.dart:48:5)
#1      PubGlobal.run (package:grinder/grinder_sdk.dart:461:12)
#2      test (file:///Users/zoechi/dart/customers/mycustomer/myproject/my_project/tool/grind.dart:103:18)
#3      test (package:bwu_grinder_tasks/bwu_grinder_tasks.dart:63:27)
Failed to reactivate grinder 0.8.0+3: Failed to precompile grinder:init:

Reactivating pub_mediator 1.0.0...
Precompiling executables... 
Failed to precompile pub_mediator:args:
Unable to find 'main' in root library 'file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/pub_mediator-1.0.0/bin/args.dart'
Precompiled pub_mediator:main.
Failed to reactivate pub_mediator 1.0.0: Failed to precompile pub_mediator:args:
Unable to find 'main' in root library 'file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/pub_mediator-1.0.0/bin/args.dart'
Reactivating sass 1.0.0-beta.2...
Precompiling executables... 
Failed to precompile sass:sass:

Failed to reactivate sass 1.0.0-beta.2: Failed to precompile sass:sass:

Reactivating stagehand 1.1.6...
Precompiling executables... 
Precompiled stagehand:stagehand.
Installed executable stagehand.
Binstubs exist for non-activated packages:
  From coverage: collect_coverage and format_coverage
  From sass: dart-sass
  From grinder: grind
  From pub_mediator: mediator
  From bwu_analysis_options_updater: repo and update_analysis_options
Reactivated 2 packages.
Failed to reactivate 4 packages:
- coverage
- grinder
- pub_mediator
- sass
```

`pub global activate grinder` caused

```
(built_value) $ pub global activate grinder
Resolving dependencies... (3.4s)
+ ansicolor 0.0.9
+ args 0.13.7 (1.0.0 available)
+ async 1.13.3 (2.0.0 available)
+ charcode 1.1.1
+ collection 1.14.3
+ glob 1.1.3
+ grinder 0.8.0+3
+ logging 0.11.3+1
+ mockable_filesystem 0.0.3
+ path 1.4.2
+ source_span 1.4.0
+ string_scanner 1.0.2
+ supports_color 0.1.1
+ unscripted 0.6.2
Precompiling executables... 
Failed to precompile grinder:init:

Failed to precompile grinder:grinder:

failed with exit code 1
#0      run (package:grinder/src/run.dart:48:5)
#1      PubGlobal.run (package:grinder/grinder_sdk.dart:461:12)
#2      test (file:///Users/zoechi/dart/customers/mycustomer/myproject/my_project/tool/grind.dart:103:18)
#3      test (package:bwu_grinder_tasks/bwu_grinder_tasks.dart:63:27)
zoechi@mac ~/dart/customers/mycustomer/myproject/my_project
```

when I step out of the project directory and run `pub global activate grinder` I get

```
 (built_value) $ pub global activate grinder
Package grinder is currently active at version 0.8.0+3.
Resolving dependencies... (3.5s)
+ ansicolor 0.0.9
+ args 0.13.7 (1.0.0 available)
+ async 1.13.3 (2.0.0 available)
+ charcode 1.1.1
+ collection 1.14.3
+ glob 1.1.3
+ grinder 0.8.0+3
+ logging 0.11.3+1
+ mockable_filesystem 0.0.3
+ path 1.4.2
+ source_span 1.4.0
+ string_scanner 1.0.2
+ supports_color 0.1.1
+ unscripted 0.6.2
Precompiling executables... 
Failed to precompile grinder:init:

Failed to precompile grinder:grinder:
Error: expected to find 'tool/grind.dart' relative to the current directory.
```

that it is related to the latest Dart update is just a suspicion, but I updated within the last hour.

**Comment by zoechi** [comment]
Switching back to `Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:47:12 2017) on "macos_x64"` fixed it

**Comment by jakemac53** [comment]
There was an issue with snapshot generation that could possibly be related, see https://github.com/dart-lang/sdk/issues/30790

**Comment by jakemac53** [comment]
Ya I found that error message and its trying to generate a snapshot, this should be fixed in the next release which should be soon as we are delaying the 2.x official announcement until its fixed.

**Comment by zoechi** [comment]
thanks
dup of dart-lang/sdk#30790

**Comment by andesappal** [comment]
Hi when I run `flutter pub cache repair` I get
```
For solutions, see https://dart.dev/go/unsound-null-safety
Reactivating fvm 2.0.4...
Precompiling executables...
Failed to precompile fvm:main:
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.4/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.4/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Failed to reactivate fvm 2.0.4: Failed to precompile fvm:main:
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.4/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.4/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Binstubs exist for non-activated packages:
  From devtools: devtools
  From fvm: fvm
Failed to reactivate 2 packages:
- devtools
- fvm
pub finished with exit code 69
```

`flutter doctor` says
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!
```

I don't want to have anything to do with FVM any longer, but apparently the repair still wants to reactivate `fvm` and maybe the old `devtools`? Why? Need help, thanks.
