### ISSUE TITLE
flutter pub pub publish throw exception

### ISSUE THREAD

**Issue by gooking** [dart-lang/pub#2202]
`    | Then click "Allow access".
    |
    | Waiting for your authorization...
MSG : Authorization received, processing...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.4.0
ERR : The setter 'readEventsEnabled=' was called on null.
    | Receiver: null
    | Tried calling: readEventsEnabled=false
FINE: Exception type: NoSuchMethodError
ERR : dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                StreamView.listen
    | package:shelf/shelf_io.dart 64:14         serveRequests.<fn>
    | package:shelf/src/util.dart 24:20         catchTopLevelErrors
    | package:shelf/shelf_io.dart 63:3          serveRequests
    | package:pub/src/oauth2.dart 198:5         _authorize.<fn>
    | dart:async                                _completeOnAsyncReturn
    | package:pub/src/io.dart                   bindServer
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 197:30        _authorize
    | package:pub/src/oauth2.dart 127:41        _getClient
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/oauth2.dart 125:26        _getClient
    | package:pub/src/oauth2.dart 96:10         withClient
    | package:pub/src/command/lish.dart 66:13   LishCommand._publish
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/command/lish.dart 63:18   LishCommand._publish
    | package:pub/src/command/lish.dart 142:13  LishCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:pub/src/command/lish.dart         LishCommand.run
    | package:args/command_runner.dart 194:27   CommandRunner.runCommand
ERR : This is an unexpected error. Please run
    |
    |     pub --trace publish -v
    |
    | and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:190:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:223:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

**Comment by gooking** [comment]
flutter pub pub publish --dry-run 

Package has 0 warnings.

**Comment by gooking** [comment]
resolved by socket5 proxy
