### ISSUE TITLE
`pub global` shouldn't show stack track on exception

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#2766]
Dart SDK version: 2.12.0-51.0.dev (dev) (Mon Nov 16 20:28:53 2020 -0800) on "macos_x64"

```console
> pub global ; echo $?
Unhandled exception:
Missing subcommand for "pub global".

Usage: pub global [arguments...]
-h, --help    Print this usage information.

Available subcommands:
  activate     Make a package's executables globally available.
  deactivate   Remove a previously activated package.
  list         List globally activated packages.
  run          Run an executable from a globally activated package.

Run "pub help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-global for detailed documentation.
#0      Command.usageException (package:args/command_runner.dart:399:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:160:19)
#2      PubCommandRunner.runCommand (package:pub/src/command_runner.dart:147:24)
#3      PubCommandRunner.run (package:pub/src/command_runner.dart:136:18)
#4      main (file:///b/s/w/ir/cache/builder/sdk/third_party/pkg/pub/bin/pub.dart:9:48)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
255
```

print help, fine. non-zero exit code, fine. But no stack trace.

The exit code should be `64` - improper usage 😄

**Comment by sigurdm** [comment]
Seems this broke with 492011209a0c50addecddbeffac4ceea75561122 .

**Comment by kevmoo** [comment]
Thanks @sigurdm !
