### ISSUE TITLE
Indefinite stall OR Error 66 on flutter pub publish

### ISSUE THREAD

**Issue by azan-n** [dart-lang/pub#3172]
# Environment

- `flutter pub version` Pub 2.14.3

- OS version:  Ubuntu 20.04 LTS, Windows 10 Pro 20H2
- Are you using the Chinese community mirror or a corporate firewall? **No.**

# Problem
I am building a package with the 'plugin' template and am unable to push to it pub.dev. As of now, if I run `flutter pub publish --dry-run -v` or  `flutter pub pub publish --dry-run -v` on Ubuntu, even after running `flutter pub cache repair` and `flutter pub pub cache repair`, I get the following log:

```
[  +17 ms] executing: [/home/zues/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +165 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' `is` not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +145 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +74 ms] Using /home/zues/snap/flutter/common/flutter/.pub-cache for the pub cache.
[        ] executing: /home/zues/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub publish --dry-run -v
FINE: Pub 2.14.3
FINE: Archiving and publishing Instance of 'Package'.
MSG : Publishing lexactivator 3.0.0 to https://pub.dartlang.org:
***insert directory tree here
FINE: Creating .tar.gz stream containing:
***insert project files here
IO  : Spawning "git --version" in /home/zues/lexactivator/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 2.17.1
    | Nothing output on stderr.
FINE: Determined git command git.
IO  : Spawning "git check-ignore --quiet ." in /home/zues/lexactivator/.
IO  : Finished git. Exit code 1.
    | Nothing output on stdout.
    | Nothing output on stderr.
IO  : Spawning "git ls-files --cached --exclude-standard --recurse-submodules" in /home/zues/lexactivator/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .gitignore
    | | CHANGELOG.md
    ***insert project files here
    | Nothing output on stderr.

```
The command then stalls. I have left the system as is for an hour with no yield.
This is my project root pubspec (not the example pubspec):
```yaml
name: lexactivator
description: LexActivator API wrapper for Dart. Integrates Crypltex's services into the Dart language.
version: 3.0.0
homepage: https://cryptlex.com

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffigen: ^4.0.0  

dev_dependencies:
  flutter_lints: ^1.0.0
  
  
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LexactivatorPlugin
      macos:
        pluginClass: LexactivatorPlugin
      windows:
        pluginClass: LexactivatorPlugin

```

Furthermore, on Windows, the same commands as above yield:

```
ERR : Directory listing failed, path = '.\example\windows\flutter\ephemeral\.plugin_symlinks\lexactivator\example\windows\flutter\ephemeral\.plugin_symlinks\lexactivator\example\windows\flutter\ephemeral\.plugin_symlinks\lexactivator\windows\include\lexactivator\*' (OS Error: The system cannot find the path specified.
    | , errno = 3)
FINE: Exception type: FileSystemException
FINE: dart:io
 _Directory.listSync
    | package:pub/src/validator/gitignore.dart 43:50
 GitignoreValidator.validate.<fn>
    | package:pub/src/ignore.dart 293:28
 Ignore.listFiles
    | package:pub/src/validator/gitignore.dart 41:43
 GitignoreValidator.validate
    | package:pub/src/validator.dart 156:64
 Validator.runAll.<fn>
    | dart:async
 Future.wait
    | package:pub/src/validator.dart 156:19
 Validator.runAll
    | package:pub/src/command/lish.dart 245:21
 LishCommand._validate
    | package:pub/src/command/lish.dart 219:15
 LishCommand.runProtected
    | dart:async
 new Future.sync
    | package:pub/src/utils.dart 112:12
 captureErrors.wrappedCallback
    | package:stack_trace
 Chain.capture
    | package:pub/src/utils.dart 125:11
 captureErrors
    | package:pub/src/command.dart 171:13
 PubCommand.run
    | package:args/command_runner.dart 209:27
 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168:24
 PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 153:20
 PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56
 runDartdev
    | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9 
 main
    | ===== asynchronous gap ===========================
    | dart:async
 Future.catchError
    | package:pub/src/utils.dart 112:52
 captureErrors.wrappedCallback
    | package:stack_trace
 Chain.capture
    | package:pub/src/utils.dart 125:11
 captureErrors
    | package:pub/src/command.dart 171:13
 PubCommand.run
    | package:args/command_runner.dart 209:27
 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168:24
 PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 153:20
 PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56
 runDartdev
    | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9 
 main
[+8233 ms] "flutter publish" took 8,334ms.
[   +4 ms] pub finished with exit code 66
[   +2 ms] 
           #0      throwToolExit
           (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively
           (package:flutter_tools/src/dart/pub.dart:391:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand
           (package:flutter_tools/src/commands/packages.dart:247:5)   
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>

(package:flutter_tools/src/runner/flutter_command.dart:1125:27)       
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)       
           <asynchronous suspension>
           #5      CommandRunner.runCommand
           (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)  
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)       
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand

(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)  
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>        
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)       
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)  
           <asynchronous suspension>


[ +236 ms] ensureAnalyticsSent: 229ms
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 66
```

## Expected behaviour

As there is scarce documentation about the fine-details of the pub publish command (which might not be required), as per what I have found on the internet, I expect the command to at least stop with errors yet it just stalls on Ubuntu, and on Windows it throws an error I haven't found much data about.

I was on the latest dev channel release at first which I thought was the cause of the problem but I switched to stable and even rebuilt the project to try again but had no luck so far.

**Comment by azan-n** [comment]
I've found the root cause of the problem and the issue can definitely be recreated, I kept `flutter pub publish` program running on Linux for a considerable amount of time to run into an actual error and not just a stall. I got the following logs from it
```
SLVR:         selecting ffi 1.1.2
SLVR:           selecting vector_math 2.1.0
SLVR:           fact: typed_data >=1.3.0 depends on collection ^1.15.0
SLVR:             selecting typed_data 1.3.0
SLVR:               selecting sky_engine 0.0.99 from sdk
SLVR:                 selecting meta 1.7.0
SLVR:                   selecting collection 1.15.0
SLVR:                     selecting characters 1.2.0
SLVR: Version solving took 0:00:03.004610 seconds.
    | Tried 1 solutions.
ERR : Directory listing failed, path = './example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/windows/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/windows/flutter/ephemeral/.plugin_symlinks/lexactivator/example/windows/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/windows/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/linux/flutter/ephemeral/.plugin_symlinks/lexactivator/example/windows/flutter/ephemeral/.plugin_symlinks/lexactivator/.git/objects/4a/' (OS Error: Too many levels of symbolic links, errno = 40)
FINE: Exception type: FileSystemException
FINE: dart:io                                                        _Directory.listSync
    | package:pub/src/validator/gitignore.dart 43:50                 GitignoreValidator.validate.<fn>
    | package:pub/src/ignore.dart 293:28                             Ignore.listFiles
    | package:pub/src/validator/gitignore.dart 41:43                 GitignoreValidator.validate
    | package:pub/src/validator.dart 156:64                          Validator.runAll.<fn>
    | dart:async                                                     Future.wait
    | package:pub/src/validator.dart 156:19                          Validator.runAll
    | package:pub/src/command/lish.dart 245:21                       LishCommand._validate
    | package:pub/src/command/lish.dart 219:15                       LishCommand.runProtected
    | dart:async                                                     new Future.sync
    | package:pub/src/utils.dart 112:12                              captureErrors.wrappedCallback
    | package:stack_trace                                            Chain.capture
    | package:pub/src/utils.dart 125:11                              captureErrors
    | package:pub/src/command.dart 171:13                            PubCommand.run
    | package:args/command_runner.dart 209:27                        CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168:24                     PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 153:20                     PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56                             runDartdev
    | /b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
    | ===== asynchronous gap ===========================
    | dart:async                                                     Future.catchError
    | package:pub/src/utils.dart 112:52                              captureErrors.wrappedCallback
    | package:stack_trace                                            Chain.capture
    | package:pub/src/utils.dart 125:11                              captureErrors
    | package:pub/src/command.dart 171:13                            PubCommand.run
    | package:args/command_runner.dart 209:27                        CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168:24                     PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 153:20                     PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56                             runDartdev
    | /b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
[+7737392 ms] "flutter publish" took 77,37,669ms.
[  +10 ms] pub finished with exit code 66
[   +5 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively
           (package:flutter_tools/src/dart/pub.dart:391:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand
           (package:flutter_tools/src/commands/packages.dart:247:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +257 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 66
```

## The problem
On both Windows and Linux, it seems that the publish command was going through the `./example/<OS-specific folder>/flutter/ephemeral/.plugin_symlink` recursively as the symlink only points to the upper folder which is the plugin itself.
Deleting the folder lead to an error fixed the problem for me, it is anyway supposed to be kept out of version control so that shouldn't be a problem.

Anyway, I ended up uploading my plugin at [pub.dev](https://pub.dev/packages/lexactivator). 

It says [here](https://dart.dev/tools/pub/publishing) that all files in `.gitignore` and `.pubignore` are not published yet the `pub publish` command chose to enter a directory ignored by `.gitignore`. It did end up publishing the directory in my [plugin](https://storage.googleapis.com/pub-packages/packages/lexactivator-3.0.0.tar.gz) which you can find inside the tar.gz which I did not expect to happen.

**Comment by sigurdm** [comment]
We should not follow symlinks here.

**Comment by sigurdm** [comment]
> It says here that all files in .gitignore and .pubignore are not published yet the pub publish command chose to enter a directory ignored by .gitignore. It did end up publishing the directory in my plugin which you can find inside the tar.gz which I did not expect to happen.

This sounds like a separate issue.

Can you replicate this in a small example?

Maybe the issue is that if both a `.gitignore` and a `.pubignore` exists in the same dir, only the `.pubignore` is taken into account...

**Comment by azan-n** [comment]
> This sounds like a separate issue.
> 
> Can you replicate this in a small example?
> 
> Maybe the issue is that if both a `.gitignore` and a `.pubignore` exists in the same dir, only the `.pubignore` is taken into account...

I don't entirely understand the internal workings of `pub` and the documentation leaves much to be desired. As such it seems that the documentation implies that anything in a .gitignore is ignored when publishing using `pub publish` but that does not seem to be the case. I can recreate the issue in the following steps:

1. `flutter create -t plugin --platforms=android,ios,windows,linux,macos example-plugin` (for some reason I cannot name my plugin example but that is for another issue I suppose)
2. `cd example_plugin` and `cd example`
3. `flutter run`
4. `cd ..` and `flutter pub publish`

I am not using a .pubignore with a .gitignore so that is not part of the problem.
Deleting the .plugin_symlinks before publishing works well for me.

Love from [Cryptlex](cryptlex.com)

**Comment by sigurdm** [comment]
Thanks for the reproduction.

What specific folder is it that gets published but is ignored by a gitignore?

> the documentation leaves much to be desired

We are doing our best - if you have concrete examples of missing/wrong documentation you are welcome to file issues, and we will see what we can do to improve the docs.

If a file is ignored by a gitignore but published anyways, then it is not the docs that are wrong but the implementation.
