### ISSUE TITLE
Error when running build runner "Null check operator used on a null value"

### ISSUE THREAD

**Issue by balenaultra** [dart-lang/pub#3314]
After Flutter upgrade and "flutter pub run build_runner build --delete-conflicting-outputs"

```
Null check operator used on a null value
package:pub/src/package_graph.dart 70:53                         PackageGraph.transitiveDependencies.<fn>.<fn>
dart:core                                                        Iterable.toSet
package:pub/src/package_graph.dart 70:56                         PackageGraph.transitiveDependencies.<fn>
package:pub/src/utils.dart 622:41                                mapMap
package:pub/src/package_graph.dart 68:11                         PackageGraph.transitiveDependencies
package:pub/src/package_graph.dart 100:12                        PackageGraph.isPackageMutable
package:pub/src/executable.dart 100:33                           runExecutable
package:pub/src/command/run.dart 88:26                           RunCommand.runProtected
package:pub/src/command.dart 180:45                              PubCommand.run.<fn>
package:pub/src/command.dart 180:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 180:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
package:dartdev/dartdev.dart 46:56                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. Please run

    dart pub --trace run build_runner build --delete-conflicting-outputs

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub finished with exit code 1
```

After run "dart pub --trace run build_runner build --delete-conflicting-outputs"

```
Deprecated. Use `dart run` instead.
Null check operator used on a null value
package:pub/src/package_graph.dart 70:53   PackageGraph.transitiveDependencies.<fn>.<fn>
dart:core                                  Iterable.toSet
package:pub/src/package_graph.dart 70:56   PackageGraph.transitiveDependencies.<fn>
package:pub/src/utils.dart 622:41          mapMap
package:pub/src/package_graph.dart 68:11   PackageGraph.transitiveDependencies
package:pub/src/package_graph.dart 100:12  PackageGraph.isPackageMutable
package:pub/src/executable.dart 100:33     runExecutable
package:pub/src/command/run.dart 88:26     RunCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace pub --trace run build_runner build --delete-conflicting-outputs

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [versÃ£o 10.0.19042.1526], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)   
[√] Android Studio (version 4.1)
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!`
```

**Comment by AdrielSchneider** [comment]
Delete your build folder and execute `flutter pub get` to update your dependencies.

**Comment by sigurdm** [comment]
pub should not crash here. Are you able to reproduce this reliably?

**Comment by balenaultra** [comment]
All of my projcts have the same problem.
So I deleted the build folder.
Now there is another message

```
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\dev\XXXXX\android\app\build.gradle:
android {
  compileSdkVersion 31
  ...
}

```
I change compileSdkVersion version to 31  on `android\app\build.gradle`.

After that, the new message is:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platform_device_id:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                       │
│ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then │
│ update C:\dev\xxxxxx\android\build.gradle:                              │
│ ext.kotlin_version = '<latest-version>'                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
```

So I changed Kotlin version to 1.6.10 on  `android\build.gradle` and it works.

The bad news is that I have to do that on all of my projects. 

Thanks

**Comment by sigurdm** [comment]
@balenaultra I think that now sounds like a flutter issue, and should probably be filed under https://github.com/flutter/flutter/issues/new .

**Comment by epkalibbala** [comment]
This worked for me: 

flutter clean,
flutter pub get, 
flutter pub run build_runner build

In that very order, in the respective terminals.

**Comment by Muraveiko** [comment]
I get this error too. 
Null check operator used on a null value
package:source_gen/src/type_checker.dart 177:74                      TypeChecker.isExactlyType
package:floor_generator/misc/type_utils.dart 32:43                   StreamTypeChecker.isStream
package:floor_generator/processor/query_method_processor.dart 43:41  QueryMethodProcessor.process

My wrong code :
```
  @Query("DELETE FROM inn_info WHERE inn=:innInfo.inn")
  void delete(InnInfo innInfo);

```

**Comment by erfanegtfi** [comment]
Any fix for this issue??
We can't clean project every time.

**Comment by MuhammedKpln** [comment]
Having same issue as well, tried to upgrade all packages that is using build_runner but no luck. Need to clean project every time to be able to run. running with --verbose does not either any valuable information about why is this happening. 



```bash
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (7 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

```

**Comment by sigurdm** [comment]
Can other's with this problem confirm that they were using the flutter_gen package?
(hoping this is the only bug 🤞)
@balenaultra @AdrielSchneider @epkalibbala and others?

**Comment by trongnghiagenki** [comment]
> Can other's with this problem confirm that they were using the flutter_gen package? (hoping this is the only bug 🤞) @balenaultra @AdrielSchneider @epkalibbala and others?

Yes, I can confirm it. Got the same error when I used flutter_gen 5.3.0.

Fixed by changing package name https://github.com/FlutterGen/flutter_gen/issues/373#issuecomment-1521903743

**Comment by includelife1** [comment]
This error can occurs when have wrong path in pubspec.yaml assest part. Remove all wrong paths and try again. It worked for me.

**Comment by sigurdm** [comment]
@includelife1 what version of Flutter are you on? Can you make a reproduction?

**Comment by Lyxng69** [comment]
> > Can other's with this problem confirm that they were using the flutter_gen package? (hoping this is the only bug 🤞) @balenaultra @AdrielSchneider @epkalibbala and others?
> 
> Yes, I can confirm it. Got the same error when I used flutter_gen 5.3.0.
> 
> Fixed by changing package name [FlutterGen/flutter_gen#373 (comment)](https://github.com/FlutterGen/flutter_gen/issues/373#issuecomment-1521903743)

thanks, this work for me. i've tried to run pub get every time i need run build runner

**Comment by chillbrodev** [comment]
I am running Flutter 3.10.5 and have started seeing this on my Bitrise CI. I cache the flutter sdk so I do not need to install fresh each time. Haven't seen this happen locally before.

**Comment by Gray-Codev-29** [comment]
any updates on this?,  using flutter gen as well

**Comment by sigurdm** [comment]
@Gray-Codev-29 try using https://pub.dev/packages/flutter_gen_runner instead.

**Comment by EArminjon** [comment]
I use `build_runner` and `generate: true`because of l10n, generate true is used allow the `flutter pub get` command to reload when called automatically the translations.


I can't replace flutter_gen by flutter_gen_runner  because of the following exception :
```
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/earminjon/IdeaProjects/untitled/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:232:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///Users/earminjon/.pub-cache/hosted/pub.dev/build_runner-2.3.3/bin/build_runner.dart:27:30)
<asynchronous suspension>
pub finished with exit code 255
```

**Comment by EArminjon** [comment]
pubspec.yaml
```yaml
name: untitled
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  #huawei_location:
   #  path: forked/huawei_location

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  # work
  #flutter_gen: ^5.1.0+1
  # not work
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true
  generate: true
```

**Comment by anasboyka** [comment]
for me i used **swagger_dart_code_generator**  package and without the json file.. so i just remove the package and it works

**Comment by sigurdm** [comment]
After https://github.com/flutter/flutter/issues/102983 there should be no more issues around flutter_gen
