### ISSUE TITLE
Can't create new flutter app using very good cli

### ISSUE THREAD

**Issue by kthirirania** [dart-lang/pub#3573]
# Environment

- Dart version: Dart SDK version: 2.18.1 (stable)
- OS kind and version: windows_x64 11
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

## Expected behavior

App creation

## Actual behavior

Error

## --trace output

```
⠏ Bootstrapping... (0.7s)Unhandled exception:
Unable to execute hook: C:/Users/Rani.Kthiri/AppData/Local/Mason/Cache/hosted/registry.brickhub.dev/very_good_core_0.1.1\hooks\pre_gen.dart.
Error: 'HookContext' isn't a type.
void run(HookContext context) {
         ^^^^^^^^^^^
#0      GeneratorHooks._runHook (package:mason/src/hooks.dart:320:7)
<asynchronous suspension>
#1      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:175:5)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#3      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:141:18)
<asynchronous suspension>
#4      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:88:14)
<asynchronous suspension>
#5      main (file:///C:/Users/Rani.Kthiri/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/very_good_cli-0.8.0/bin/very_good.dart:5:24)
<asynchronous suspension>
⠏ Bootstrapping... (0.7s)Unhandled exception:
Unable to execute hook: C:/Users/Rani.Kthiri/AppData/Local/Mason/Cache/hosted/registry.brickhub.dev/very_good_core_0.1.1\hooks\pre_gen.dart.
Error: 'HookContext' isn't a type.
void run(HookContext context) {
         ^^^^^^^^^^^
#0      GeneratorHooks._runHook (package:mason/src/hooks.dart:320:7)
<asynchronous suspension>
#1      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:175:5)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#3      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:141:18)
<asynchronous suspension>
#4      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:88:14)
<asynchronous suspension>
#5      main (file:///C:/Users/Rani.Kthiri/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/very_good_cli-0.8.0/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Comment by pech84** [comment]
Hi,
I also get this problem, did you solve it?

**Comment by sigurdm** [comment]
Not sure this is a pub client problem. Have you tried reporting to the issue tracker of very_good_cli?

https://github.com/VeryGoodOpenSource/very_good_cli
