### ISSUE TITLE
Cannot use git depenency with path and ref together

### ISSUE THREAD

**Issue by rekire** [dart-lang/pub#3627]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 2.19.0-255.2.beta (beta) (Tue Oct 4 13:45:53 2022 +0200) on "windows_x64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): Microsoft Windows 10 (Build19044.2130)
- Are you using the Chinese community mirror or a corporate firewall? Nope

# Problem

I cannot replace a dependency with a git dependency which has a ref (git branch) **and** a path. It just works with on of them:

```yaml
dependencies:
  # ...
  flutter_webview_pro: #^3.0.1+4
    git:
      url: https://github.com/rekire/flutter-plugins-fork.git
      ref: self_camera_check
      path: packages/rekire/flutter-plugins-fork
```

## Expected behavior

I expect that I can checkout that feature branch.

## Actual behavior

The sync fetches forever:

```
Running "flutter pub get" in central_planner_flutter...         
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...
pub get failed (server unavailable) -- attempting retry 10 in 64 seconds...
pub get failed (server unavailable) -- attempting retry 11 in 64 seconds...
...
```

**Comment by sigurdm** [comment]
Can you try running `flutter pub pub get --verbose` to see what is going on.

**Comment by rekire** [comment]
I accidentally forked the repo in a wrong organization so I had to delete the repo there and pushed it into my "namespace". However now it became more confusing.

Now I get the error:
```
pub get failed
command: "C:\SDKs\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\SDKs\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\rekire\AppData\Local\Pub\Cache",
}
exit code: 66
last line of pub output: "Could not find a file named "pubspec.yaml" in "C:\Users\rekire\AppData\Local\Pub\Cache\git\flutter-plugins-fork-5292ea2dde45952ee8914ee836a7e56170401e06\packages\webview_flutter\webview_flutter_android"."
```

That does not make sense. That file exists in that [branch](https://github.com/rekire/flutter-plugins-fork/tree/self_camera_check/packages/webview_flutter/webview_flutter) with that [commit hash](https://github.com/rekire/flutter-plugins-fork/tree/5292ea2dde45952ee8914ee836a7e56170401e06/packages/webview_flutter/webview_flutter) from the folder name. However I can confirm that the path does not exists on my local disk. Based on the content it seems to be a veeeeery old version (about 1-2years) of the master branch which I synced already and does not exists anymore. When I delete the folder it get recovered with exact the same wrong (for the hash of the url) content.

I already tried a `dart pub cache repair` without success. Anyway here is my new verbose output:

```
...lots of hopefully unreleased stuff...
FINE: Resolving dependencies finished (2.271s).
MSG :   async 2.9.0 (2.10.0 available)
    |   boolean_selector 2.1.0 (2.1.1 available)
    |   collection 1.16.0 (1.17.0 available)
    |   device_info 2.0.3 (discontinued)
    | * flutter_webview_pro 3.0.4+1 from git https://github.com/rekire/flutter-plugins-fork.git at 5292ea in packages/webview_flutter/webview_flutter (was 3.0.4+1 from git https://github.com/rekire/webview_pro_fork.git at 5292ea in packages/w
ebview_flutter/webview_flutter)
    |   js 0.6.4 (0.6.5 available)
    |   matcher 0.12.12 (0.12.13 available)
    |   package_info 2.0.2 (discontinued)
    |   sentry 6.13.1 (6.14.0 available)
    |   sentry_flutter 6.13.1 (6.14.0 available)
    |   stack_trace 1.10.0 (1.11.0 available)
    |   string_scanner 1.1.1 (1.2.0 available)
    |   test_api 0.4.14 (0.4.16 available)
WARN: Warning: You are using these overridden dependencies:
    | ! webview_pro_android 2.10.4+1 from git https://github.com/rekire/flutter-plugins-fork.git at 5292ea in packages/webview_flutter/webview_flutter_android
IO  : Spawning "cmd /c git rev-parse --is-inside-git-dir" in C:\Users\rekire\AppData\Local\Pub\Cache\git\cache\autologin_plugin-69aafbf16d6e22f8961b4188bc207c5cdc47d709
IO  : Finished git. Exit code 0.
    | stdout:
    | | true
    | Nothing output on stderr.
IO  : Spawning "cmd /c git rev-list --max-count=1 8eae6c2d914235d699029238aacbaa2539361b57" in C:\Users\rekire\AppData\Local\Pub\Cache\git\cache\autologin_plugin-69aafbf16d6e22f8961b4188bc207c5cdc47d709
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/path
    | took 0:00:00.312091
    | x-powered-by: Dart with package:shelf
    | transfer-encoding: chunked
    | date: Fri, 04 Nov 2022 22:27:36 GMT
    | content-encoding: gzip
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
IO  : Finished git. Exit code 0.
    | stdout:
    | | 8eae6c2d914235d699029238aacbaa2539361b57
    | Nothing output on stderr.
ERR : Could not find a file named "pubspec.yaml" in "C:\Users\rekire\AppData\Local\Pub\Cache\git\flutter-plugins-fork-5292ea2dde45952ee8914ee836a7e56170401e06\packages\webview_flutter\webview_flutter_android".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 306:7                     new Pubspec.load
    | package:pub/src/package.dart 128:29                    new Package.load
    | package:pub/src/source/git.dart 331:22                 GitSource.downloadToSystemCache.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.catchError
    | package:pub/src/utils.dart 109:52                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 122:11                      captureErrors
    | package:pub/src/command.dart 189:13                    PubCommand.run
    | package:args/command_runner.dart 209:27                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 176:24             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 161:20             PubCommandRunner.run
    | package:dartdev/dartdev.dart 48:47                     runDartdev
    | C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
IO  : Writing 246200 characters to text file C:\Users\rekire\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\rekire\AppData\Local\Pub\Cache\log\pub_log.txt.
[ +511 ms] "flutter get" took 3.741ms.
[   +4 ms] pub get failed
           command: "E:\SDKs\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --verbose --directory . get --example"
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1244:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +51 ms] ensureAnalyticsSent: 48ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1244:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +51 ms] ensureAnalyticsSent: 48ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 66

```

**Comment by sigurdm** [comment]
Trying to reproduce this I think the problem is the broken path.

Try:
```
dependencies:
  flutter_webview_pro: #^3.0.1+4
    git:
      url: https://github.com/rekire/flutter-plugins-fork.git
      ref: self_camera_check
      path: packages/webview_flutter/webview_flutter # <== this was wrong.
```

With n upstream Flutter you should also not see the infinite retries (that was fixed recently).
