### ISSUE TITLE
OS Error: No Such file or directory on 'flutter pub run build_runner' command

### ISSUE THREAD

**Issue by sbatezat** [dart-lang/pub#3978]
# Environment

- Dart version : 3.0.6
- OS kind and version : Ubuntu 22.04.2 LTS (docker container)
- Are you using the Chinese community mirror or a corporate firewall : No

# Problem

I'm posting the issue here according to @jakemac53 advices.
Please see bellow my stacktrace for the command : flutter pub run build_runner build --verbose

It's not working and the issue seems easy to understand.
First, it's moving a file from ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB

`IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".`

Before it's ended, it's removing it :

`IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
`

We then have obviously this error, telling us we cannot move a file which doesn't exists anymore.

`ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)`

Please note it's failing on my GitlabCi (docker container with Ubuntu) while it's working on my MacOS M2.
My MacOS is obviously faster to move that directory. 

## Expected behavior

Build runner success.

## Actual behavior

Build runner failure

## --trace output

```
[   +6 ms] executing: [/sdks/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] executing: [/sdks/flutter/] git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[  +97 ms] Exit code 0 from: git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] 3.10.6
[   +3 ms] executing: [/sdks/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[        ] executing: [/sdks/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[   +6 ms] executing: uname -m
[  +68 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +175 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +114 ms] executing: [/builds/project/packages/domain/] /sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose
FINE: Pub 3.0.6
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB
MSG : Built build_runner:build_runner.
IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".
IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)
FINE: Exception type: PathNotFoundException
FINE: dart:io                                              _File.renameSync
    | package:pub/src/io.dart 534:14                       renameFile
    | package:pub/src/dart.dart 162:7                      precompile
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.catchError
    | package:pub/src/utils.dart 150:21                    waitAndPrintErrors.<fn>
    | dart:async                                           Future.wait
    | package:pub/src/utils.dart 148:17                    waitAndPrintErrors
    | package:pub/src/entrypoint.dart 494:14               Entrypoint.precompileExecutable.<fn>
    | package:pub/src/log.dart 438:18                      progress
    | package:pub/src/entrypoint.dart 492:15               Entrypoint.precompileExecutable
    | package:pub/src/command/run.dart 106:26              RunCommand.runProtected.<fn>.<fn>
    | package:pub/src/log.dart 421:32                      errorsOnlyUnlessTerminal
    | package:pub/src/command/run.dart 105:38              RunCommand.runProtected.<fn>
    | package:pub/src/executable.dart 97:22                runExecutable
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/executable.dart 93:5                 runExecutable
    | package:pub/src/command/run.dart 100:26              RunCommand.runProtected
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/command/run.dart 61:7                RunCommand.runProtected
    | package:pub/src/command.dart 199:21                  PubCommand.run.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 113:12                    captureErrors.wrappedCallback
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 126:11                    captureErrors
    | package:pub/src/command.dart 198:13                  PubCommand.run
    | package:args/command_runner.dart 212:27              CommandRunner.runCommand
    | package:dartdev/dartdev.dart 226:30                  DartdevRunner.runCommand
    | package:args/command_runner.dart [122](https://gitlab-instance/-/jobs/1189712#L122):25              CommandRunner.run.<fn>
    | dart:async                                           new Future.sync
    | package:args/command_runner.dart 122:14              CommandRunner.run
    | package:dartdev/dartdev.dart 58:29                   runDartdev
    | /b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
FINE: Building package executable finished (12.096s).
---- Log transcript ----
FINE: Pub 3.0.6
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB
MSG : Built build_runner:build_runner.
IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".
IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)
FINE: Exception type: PathNotFoundException
FINE: dart:io                                              _File.renameSync
    | package:pub/src/io.dart 534:14                       renameFile
    | package:pub/src/dart.dart 162:7                      precompile
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.catchError
    | package:pub/src/utils.dart 150:21                    waitAndPrintErrors.<fn>
    | dart:async                                           Future.wait
    | package:pub/src/utils.dart 148:17                    waitAndPrintErrors
    | package:pub/src/entrypoint.dart 494:14               Entrypoint.precompileExecutable.<fn>
    | package:pub/src/log.dart 438:18                      progress
    | package:pub/src/entrypoint.dart 492:15               Entrypoint.precompileExecutable
    | package:pub/src/command/run.dart 106:26              RunCommand.runProtected.<fn>.<fn>
    | package:pub/src/log.dart 421:32                      errorsOnlyUnlessTerminal
    | package:pub/src/command/run.dart 105:38              RunCommand.runProtected.<fn>
    | package:pub/src/executable.dart 97:22                runExecutable
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/executable.dart 93:5                 runExecutable
    | package:pub/src/command/run.dart 100:26              RunCommand.runProtected
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/command/run.dart 61:7                RunCommand.runProtected
    | package:pub/src/command.dart 199:21                  PubCommand.run.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 113:12                    captureErrors.wrappedCallback
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart [126](https://gitlab-instance/jobs/1189712#L126):11                    captureErrors
    | package:pub/src/command.dart 198:13                  PubCommand.run
    | package:args/command_runner.dart 212:27              CommandRunner.runCommand
    | package:dartdev/dartdev.dart 226:30                  DartdevRunner.runCommand
    | package:args/command_runner.dart 122:25              CommandRunner.run.<fn>
    | dart:async                                           new Future.sync
    | package:args/command_runner.dart 122:14              CommandRunner.run
    | package:dartdev/dartdev.dart 58:29                   runDartdev
    | /b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
FINE: Building package executable finished (12.096s).
---- End log transcript ----
IO  : Writing 11135 characters to text file /root/.pub-cache/log/pub_log.txt.
MSG : Logs written to /root/.pub-cache/log/pub_log.txt.
[+13994 ms] pub failed
            command: "/sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose"
            pub env: {
              "FLUTTER_ROOT": "/sdks/flutter",
              "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:forward",
            }
            exit code: 66
[  +13 ms] "flutter run" took 14,305ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
           <asynchronous suspension>
           #3      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:122:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:[133](https://gitlab-instance/jobs/1189712#L133)6:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:[150](https://gitlab-instance/-/jobs/1189712#L150):19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:[212](https://gitlab-instance/jobs/1189712#L212):13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:[244](https://gitlab-instance/jobs/1189712#L244):5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
[  +74 ms] ensureAnalyticsSent: 1ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 66
```

**Comment by raffomania** [comment]
In my case, I got this exact error because I had a script generate an openapi client and then immediately run `flutter pub run build_runner build` for that code, while my VSCode Dart extension would try to run `flutter pub get`

**Comment by sbatezat** [comment]
It's not my case as there is only one action running at a time during the GitLab CI job.
It seems to be a severe issue, anyone could help?

**Comment by sigurdm** [comment]
Inspecting the code, it seems we rename the file here: https://github.com/dart-lang/pub/blob/1bfb295dabf3951745468c89019d4712d2694f3e/lib/src/dart.dart#L166 and deleting it here: https://github.com/dart-lang/pub/blob/1bfb295dabf3951745468c89019d4712d2694f3e/lib/src/dart.dart#L178

I don't think the deletion happens before the rename is done. Rather 

* renaming throws an exception, 
* the file is deleted in the "finally block" 
* and the error is printed.

The only way this can happen (I believe) is if no build result came from https://github.com/dart-lang/pub/blob/1bfb295dabf3951745468c89019d4712d2694f3e/lib/src/dart.dart#L155.

Not sure how that is possible...

Can you reproduce this reliably? Then we could dig further into this.

**Comment by sbatezat** [comment]
> Can you reproduce this reliably? Then we could dig further into this.

Yes, it crashes every time it's launch on the CI.

**Comment by sigurdm** [comment]
> Yes, it crashes every time it's launch on the CI.

Any way you can create a reproduction that we can use?

**Comment by sbatezat** [comment]
@sigurdm some interesting news here!
The stacktrace I posted on the original post was for Flutter 3.10.6 (Pub 3.0.6).
On Flutter 3.13.0 (Pub 3.1.0) renaming/deletion seems to work, and it's failing later, see :

```
[ +183 ms] executing: [/builds/app/packages/domain/] /sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose
FINE: Pub 3.1.0
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory ./.dart_tool/pub/incremental/build_runner/tmpKPJWBP
MSG : Built build_runner:build_runner.
IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpKPJWBP/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.1.0.snapshot".
IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpKPJWBP.
IO  : Writing 370 characters to text file /root/.pub-cache/README.md.
FINE: Contents:
    | Pub Package Cache
    | =================
    | 
    | This folder is used by Pub to store cached packages used in Dart / Flutter
    | projects.
    | 
    | The contents of this folder should only be modified using the `dart pub` and
    | `flutter pub` commands.
    | 
    | Modifying this folder manually can lead to inconsistent behavior.
    | 
    | For details on how manage the `PUB_CACHE`, see:
    | https://dart.dev/go/pub-cache
FINE: Building package executable finished (39.229s).
Invoked Dart programs must have a 'main' function defined:
https://dart.dev/guides/language/language-tour#a-basic-dart-program
IO  : Writing 8664 characters to text file /root/.pub-cache/log/pub_log.txt.
MSG : Logs written to /root/.pub-cache/log/pub_log.txt.
[+4[212](https://gitlab-instance/-/jobs/1198897#L212)3 ms] pub failed
            command: "/sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose"
            pub env: {
              "FLUTTER_ROOT": "/sdks/flutter",
              "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:forward",
            }
            exit code: 253
[  +68 ms] "flutter run" took 42,528ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
           <asynchronous suspension>
           #3      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:133:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
[ +116 ms] ensureAnalyticsSent: 1ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code [253](https://gitlab-instance/-/jobs/1198897#L253)
```

Once again, it's failing every time, only on one machine.
Is this help you to understand what's happening on my company's architecture?

**Comment by sbatezat** [comment]
Finally it works!
It was a RAM issue on the pod.

I've upgraded the default RAM allocated (see https://docs.gitlab.com/runner/executors/kubernetes.html#overwrite-container-resources) and everything is working fine now!

I doubt you can do anything regarding the wrong error message... I'm closing the issue.

**Comment by sigurdm** [comment]
Happy you found a solution.

Maybe we could make pub give a nicer error in case building doesn't produce the expected artifact.

**Comment by diederikMrAwesome** [comment]
We had an issue here (also when running on a CI/CD system only) when the `dart run pigeon` command was run asynchronously from bash.  It seems like the generation behaviour deletes/renames files that interfears with other dart processes.  

Our fix was to remove the '&' at the end of the bash command line.
